school_at_home/school/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.schoolView.as_view(), name='index'),
    path('<int:id>/', views.schoolDetail, name='school-detail-view' ),
    path('class/<int:id>/', views.classDetail, name='class-detail'),
]

school_at_home/school_at_home/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('school/', include('school.urls')),
]

school_at_home/school/models.py
from django.db import models
from django.urls import reverse

class school(models.Model):
    School_Name = models.CharField(max_length=50, help_text='School Name')
    School_Address = models.CharField(max_length=100, help_text='School Address')
    School_Telephone = models.CharField(max_length=20, help_text='Telephone')
    School_Email = models.EmailField()

    def __str__(self):
        return self.School_Name
    
    def get_absolute_url(self):
        return reverse('school-detail-view', args=[str(self.id)])

class ClassName(models.Model):
    ClassName = models.CharField(max_length=20, help_text='Class Name')
    schoolID = models.ForeignKey('school', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.ClassName
    
    def get_absolute_url (self):
        return reverse('class-detail', args=[str(self.id)])
    
class student(models.Model):
    Student_First_Name = models.CharField(max_length=20, help_text='First Name')
    Student_Last_Name = models.CharField(max_length=20, help_text='Last Name')
    student_dateOfBirth = models.DateField()
    Gen = (
        ('M', 'Male'),
        ('F', 'Female')
    )
    student_gender = models.CharField(max_length=10, choices=Gen)
    schoolID = models.ForeignKey('school', on_delete=models.CASCADE, null=True)
    classID = models.ForeignKey('ClassName', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.Student_First_Name} {self.Student_Last_Name}"

class teacher(models.Model):
    teacher_firstName = models.CharField(max_length=20, help_text='Teacher First Name')
    teacher_lastName = models.CharField(max_length=20, help_text='Teacher Last Name')
    teacher_email = models.EmailField()
    Ext = (
        ('mr', 'Mr.'),
        ('ms', 'Ms.'),
        ('miss', 'Miss')
    )
    extension = models.CharField(max_length=10, choices=Ext)
    classID = models.ManyToManyField('ClassName')

    def __str__(self):
        return f"{self.extension} {self.teacher_lastName}"

school_at_home/school/views.py
from django.http import Http404
from django.shortcuts import render
from django.views import generic
from .models import school, ClassName

def index(request):

    context = {}

    return render(request,'index.html', context=context)

class schoolView(generic.ListView):
    model = school


def schoolDetail(requset, id):
    try:
        x = school.objects.get(id = id)
    except school.DoesNotExist:
        raise Http404('School does not exist')
    
    context = {
        'x': x
    }
    
    return render (requset, 'school/school_detail.html', context = context)

def classDetail (request, id):
    try:
        y = ClassName.objects.get(id = id)
    except:
        raise Http404('Class does not exist')
    
    context ={
        'y': y
    }

    return render(request, 'school/class_detail.html', context = context)

school_at_home/school/templates/index.html
{% extends "layout.html" %}

{% block content %}

{% endblock %}

school_at_home/school/templates/school/class_detail.html
{% extends 'layout.html'%}

{% block content %}
<div class="col-lg-12" >
    <div class="card shadow mb-4" style="width: 100%;">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">{{y.ClassName}}</h6>
        </div>
        <div class="card-body">
            The styling for this basic card example is created by using default Bootstrap
            utility classes. By using utility classes, the style of the card component can be
            easily modified with no need for any custom CSS!
            <div>
                Teacher: 
                {% for t in y.teacher_set.all %}
                {{t.extension}} {{t.teacher_lastName}}
                {% endfor %}
            </div>

            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Student First Name</th>
                            <th>Student Last Name</th>
                            <th>Date of Birth</th>
                            <th>Gender</th>

                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Student First Name</th>
                            <th>Student Last Name</th>
                            <th>Date of Birth</th>
                            <th>Gender</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for x in y.student_set.all %}
                        <tr>
                            <td>{{x.Student_First_Name}}</td>
                            <td>{{x.Student_Last_Name}}</td>
                            <td>{{x.student_dateOfBirth}}</td>
                            <td>{{x.student_gender}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>

    </div>
</div>



{% endblock%}

school_at_home/school/templates/school/school_detail.html
{% extends 'layout.html'%}

{% block content %}
<div class="col-lg-12" >
    <div class="card shadow mb-4" style="width: 100%;">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">{{x.School_Name}}</h6>
        </div>
        <div class="card-body">
            The styling for this basic card example is created by using default Bootstrap
            utility classes. By using utility classes, the style of the card component can be
            easily modified with no need for any custom CSS!
            {{x.School_Email}} 

            <ul>
                {% for s in x.classname_set.all %}
                <li><a href="{{s.get_absolute_url}}">{{s.ClassName}}</a></li>
                {% endfor %}
            </ul>

        </div>

    </div>
</div>



{% endblock%}

school_at_home/school/templates/school/school_list.html
{% extends "layout.html" %}

{% block content %}

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-2 text-gray-800">School</h1>

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>School Name</th>
                                            <th>Address</th>
                                            <th>Telephone</th>
                                            <th>Email</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>School Name</th>
                                            <th>Address</th>
                                            <th>Telephone</th>
                                            <th>Email</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        {% for x in school_list %}
                                        <tr>
                                            <td><a href="{{x.get_absolute_url}}">{{x.School_Name}}</a></td>
                                            <td>{{x.School_Address}}</td>
                                            <td>{{x.School_Telephone}}</td>
                                            <td>{{x.School_Email}}</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

{% endblock %}